openapi: 3.0.0
info:
  title: Dokumentasi API Infotiket.in
  description: Infotiket.in adalah website penyedia pemesanan tiket pesawat terbang!
  version: 1.0.0
  contact:
    email: Infotiket.in@gmail.com
servers:
  - url: http://localhost:3000

paths:
  /api/v1/airports:
    get:
      tags:
        - "Bandara"
      summary: Daftar Semua Data Bandara

      responses:
        201:
          description: sukses
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name_airport:
                          type: string
                        city:
                          type: string
                        province:
                          type: string
                        time_zone:
                          type: string
                        iata_code:
                          type: string
                        from_flights:
                          type: array
                        to_flights:
                          type: array

              examples:
                responses:
                  value:
                    status: true
                    message: Berhasil menampilkan semua data Airports
                    data:
                      - id: 1
                        name_airport: APT Pranoto Airport
                        city: Samarinda
                        province: Kalimantan Timur
                        time_zone: UTC+8
                        iata_code: AAP
                        from_flights: []
                        to_flights: []
                      - id: 2
                        name_airport: Abdul Rachman Saleh
                        city: Malang
                        province: Jawa Timur
                        time_zone: UTC+7
                        iata_code: MLG
                        from_flights: []
                        to_flights: []

        404:
          description: Halaman Tidak Ditemukan 404
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Halaman Tidak Ditemukan 404
                  err:
                    type: string
                    example: Cannot find /api/v1/airportss
                  data:
                    type: string
                    example: null

  /api/v1/airport/{id}:
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true

    get:
      tags:
        - "Bandara"
      summary: Daftar Data Bandara ID

      responses:
        201:
          description: sukses
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: true
                  message:
                    type: string
                    example: Berhasil menampilkan semua data Airports
                  data:
                    allOf:
                      - $ref: "#/components/schemas/Bandara"

        404:
          description: Halaman Tidak Ditemukan 404
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Data Airport tidak ditemukan!
                  data:
                    type: string
                    example: null

components:
  schemas:
    Bandara:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name_airport:
          type: string
          example: APT Pranoto Airport
        city:
          type: string
          example: Samarinda
        province:
          type: string
          example: Kalimantan Timur
        time_zone:
          type: string
          example: UTC+8
        iata_code:
          type: string
          example: AAP
        from_flights:
          type: array
          example: []
        to_flights:
          type: array
          example: []
