### register
POST http://localhost:3000/register
Content-Type: application/json

{
    "first_name": "BE3",
    "last_name": "Infotiket.in",
    "email": "Infotiketin@gmail.com",
    "password": "password123"
}

### login
POST http://localhost:3000/login  
Content-Type: application/json

{
    "email": "Infotiketin@gmail.com",
    "password": "password123"
}


### halaman awal     
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImlhdCI6MTcxNjczNzQ0MH0.NxZDeyi4LRJU0MoGBA-Ihk_pn_rDfj3yEHSs3DT3ri0

