### Get Payment Methods
GET http://localhost:3000/api/v1/get-payment-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5MzIzODE4LCJleHAiOjE3MTk0MTAyMTh9.MNuaWW6rXjw3M1CUUq_RmyOk2pz9HzcQcfm-tmeW174
### Melakukan Pembayaran
POST http://localhost:3000/api/v1/pay?booking_id=1&payment_method=BRIVA
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5MzIzODE4LCJleHAiOjE3MTk0MTAyMTh9.MNuaWW6rXjw3M1CUUq_RmyOk2pz9HzcQcfm-tmeW174

### check payment
GET http://localhost:3000/api/v1/check-payment-status?merchant_ref=ef139b17-c0a8-4a01-a349-dcfab138b82f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5MTExMTg4LCJleHAiOjE3MTkxOTc1ODh9.tEfno50q4YNcsEMbRDDOxRzL6ZlrXQmV7InkA3KaPkg

### get all payment
GET http://localhost:3000/api/v1/get-payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5MzIzODE4LCJleHAiOjE3MTk0MTAyMTh9.MNuaWW6rXjw3M1CUUq_RmyOk2pz9HzcQcfm-tmeW174

### get payment data pending only
GET http://localhost:3000/api/v1/get-pending-payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5MTExMTg4LCJleHAiOjE3MTkxOTc1ODh9.tEfno50q4YNcsEMbRDDOxRzL6ZlrXQmV7InkA3KaPkg