### add passenger
POST http://localhost:3000/api/v1/addPassengers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzYsImlhdCI6MTcxNjg3MTIzNn0.
Content-Type: application/json

{
    "full_name": "infotiketin",
	"birth_date": "2023-11-1",
	"type": "adult",
	"id_passport_number": "123456789",
	"citizenship": "indonesia"
}