

### Membuat Booking dan Menambahkan Penumpang
POST http://localhost:3000/api/v1/booking?schedule_id=IN-280_false_true_false_false_false_false_false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzE5ODM3MDE4LCJleHAiOjE3MTk5MjM0MTh9.VyMRti1BihdKelkPmOgK6zTs-qcjdRFwpCmq0Q11OBA

{
  "booking_date": "2024-07-01",
  "total_passenger": 3,
  "passengers": [
    {
      "birth_date": "1990-01-01",
      "type": "Adult",
      "id_passport_number": "A1234567",
      "citizenship": "Indonesia",
      "gender": "Male",
      "first_name": "John",
      "last_name": "Doe",
      "phone_number": "08123456789"
    },
    {
      "birth_date": "2010-01-01",
      "type": "Child",
      "id_passport_number": "B2345678",
      "citizenship": "Indonesia",
      "gender": "Female",
      "first_name": "Jane",
      "last_name": "Doe",
      "phone_number": "08129876543"
    },
    {
      "birth_date": "2022-01-01",
      "type": "Infant",
      "id_passport_number": "C3456789",
      "citizenship": "Indonesia",
      "gender": "Male",
      "first_name": "Baby",
      "last_name": "Doe",
      "phone_number": "08127654321"
    }
  ]
}

### Membuat Booking Pulang-Pergi
POST http://localhost:3000/api/v1/booking?schedule_id=8B-5114_false_false_true_false_false_false_false&return_schedule_id=ID-6505_false_true_false_false_false_false_false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzE5ODk1ODg2LCJleHAiOjE3MTk5ODIyODZ9.91wNTHrClVjd3uJoVGa5eiPZ-F2sUxuhPf3FDMUgMAc

{
  "booking_date": "2024-07-01",
  "total_passenger": 3,
  "passengers": [
    {
      "birth_date": "1990-01-01",
      "type": "Dewasa",
      "id_passport_number": "A1234567",
      "citizenship": "ID",
      "gender": "MALE",
      "first_name": "John",
      "last_name": "Doe",
      "phone_number": "08123456789"
    },
    {
      "birth_date": "1995-05-05",
      "type": "Anak",
      "id_passport_number": "B7654321",
      "citizenship": "ID",
      "gender": "FEMALE",
      "first_name": "Jane",
      "last_name": "Doe",
      "phone_number": "08129876543"
    },
    {
      "birth_date": "1995-05-05",
      "type": "Anak",
      "id_passport_number": "B7654321",
      "citizenship": "ID",
      "gender": "MALE",
      "first_name": "Randy",
      "last_name": "Doe",
      "phone_number": "08129876543"
    }
  ]
}

### get all booking
GET http://localhost:3000/api/v1/get-booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5NjY5NTA5LCJleHAiOjE3MTk3NTU5MDl9.XXH_pKgf5OdP0rFBAbN1AFUPjlKTAwxTOrWqJoo1MRs

### get all booking
GET http://localhost:3000/api/v1/get-pending-booking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5MTExMTg4LCJleHAiOjE3MTkxOTc1ODh9.tEfno50q4YNcsEMbRDDOxRzL6ZlrXQmV7InkA3KaPkg

