### 
GET http://localhost:3000/api/v1/notifikasi
Content-Type: application/json
Authorization: Bearer "isi token disini"

### 
GET http://localhost:3000/api/v1/notifikasi/2
Content-Type: application/json
Authorization: Bearer "isi token disini"
