### register
POST http://localhost:3000/api/v1/auth/daftar-sekarang
Content-Type: application/json

{
    "first_name": "BE3",
    "last_name": "Infotiket.in",
    "email": "21102122@ittelkom-pwt.ac.id",
    "password": "password123",
    "confirmPassword": "password123"
}

### login
POST http://localhost:3000/api/v1/auth/masuk 
Content-Type: application/json

{
    "email": "e41212053@student.polije.ac.id",
    "password": "password123"
}

### Verification
GET http://localhost:3000/api/v1/auth/verifikasi?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5NDczMjMyfQ.qgO-l8bGmPmmDkjViVJd5Qrx_Ac2lquc_uB0eHthqTY

### first poge    
GET http://localhost:3000/api/v1/auth/halaman-utama
Authorization: Bearer "isi token disini"

### forgot password
POST http://localhost:3000/api/v1/auth/lupa-kata-sandi
Content-Type: application/json

{
    "email": "21102122@gmail.com"
}

###
POST http://localhost:3000/api/v1/auth/mengatur-ulang-kata-sandi?token="masukan token dari email disini"
Content-Type: application/json

{
    "password": "tes",
    "confirmPassword": "tes"
}