### ticket
POST http://localhost:3000/api/v1/webhook
Content-Type: application/json

{
    "merchant_ref": "191c4f3c-d287-47d4-b18c-5e962e8eda44",
    "status": "PAID"
}

### payment confirmation
GET http://localhost:3000/api/v1/payment-confirmation?bookingId=1

### search ticket with booking id
GET http://localhost:3000/api/v1/get-ticket?bookingId=1
