### cari-jadwal-penerbangan
GET http://localhost:3000/api/v1/flights?departureAirport=DPS&arrivalAirport=CGK&departureDate=2024-06-12&flightClass=EKONOMI

### cari-jadwal-penerbangan-pulang-pergi
GET http://localhost:3000/api/v1/flights?departureAirport=DPS&arrivalAirport=CGK&departureDate=2024-06-12&returnDate=2024-06-16&flightClass=EKONOMI