##
GET http://localhost:3000/api/v1/notifikasi
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5NjI1ODI3LCJleHAiOjE3MTk3MTIyMjd9.FqHWW5lIc4i1OaZAecmauZgWUGl4EadB5O_WA3lUgIY

### per id
GET http://localhost:3000/api/v1/notifikasi/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE5NjI1ODI3LCJleHAiOjE3MTk3MTIyMjd9.FqHWW5lIc4i1OaZAecmauZgWUGl4EadB5O_WA3lUgIY
