### add passenger
POST http://localhost:3000/api/v1/passengers
Content-Type: application/json

{
    "full_name": "infotiketin",
	"birth_date": "2023-06-12T15:00:00Z",
	"type": "adult",
	"id_passport_number": "123456789",
	"citizenship": "indonesia"
}