### cari-jadwal-penerbangan
GET http://localhost:3000/api/v1/flights?departureAirport=CGK&arrivalAirport=DPS&departureDate=2024-06-30&flightClass=EKONOMI&page=1&limit=10

### cari-jadwal-penerbangan-pulang-pergi
GET http://localhost:3000/api/v1/flights?departureAirport=CGK&arrivalAirport=DPS&departureDate=2024-06-30&returnDate=2024-07-1&flightClass=EKONOMI&page=1&limit=10