### get profile
GET http://localhost:3000/api/v1/profil
Cookie: token "isi token disini"



### update profile
PUT http://localhost:3000/api/v1/profil
Cookie: token "isi token disini"
Content-Type: application/json

{
    "first_name": "BE3",
    "last_name": "Infotiket.in",
    "image_url": ,
    "password": ,
    "confirmPassword": 
}

### image_url, password, dan confrim password = opsional 